{{- if .Values.postgres.enabled }}
{{- if .Values.postgres.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coco.fullname" . }}-postgres
  labels:
    {{- include "coco.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coco.fullname" . }}-postgres
  labels:
    {{- include "coco.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "coco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "coco.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image }}"
          env:
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.auth.user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.auth.password }}"
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.auth.database }}"
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "coco.fullname" . }}-postgres
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coco.fullname" . }}-postgres
  labels:
    {{- include "coco.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}
      protocol: TCP
      name: postgres
  selector:
    {{- include "coco.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
