{{- if .Values.qdrant.enabled }}
{{- if .Values.qdrant.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coco.fullname" . }}-qdrant
  labels:
    {{- include "coco.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.qdrant.persistence.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coco.fullname" . }}-qdrant
  labels:
    {{- include "coco.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "coco.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: qdrant
  template:
    metadata:
      labels:
        {{- include "coco.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: qdrant
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.qdrant.image }}"
          ports:
            - containerPort: {{ .Values.qdrant.service.port }}
          volumeMounts:
            - name: storage
              mountPath: /qdrant/storage
      volumes:
        - name: storage
          {{- if .Values.qdrant.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "coco.fullname" . }}-qdrant
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coco.fullname" . }}-qdrant
  labels:
    {{- include "coco.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.qdrant.service.port }}
      targetPort: {{ .Values.qdrant.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "coco.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
{{- end }}
